[package]
name = "gorg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
env_logger = "0.11.8"
git2 = "0.20.2"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
